markdown: kramdown
url: ''
baseurl: null
title: Jason Knoll
description: 'Discover, build, explore.'
site-image: /assets/images/meta.jpg
site-keywords: 'Site, Template, Theme'
favicon-url: null
heroimage: /assets/images/Phoenix.jpg
email: jason.p.knoll@gmail.com
facebook_username: /
twitter_username: JasonPKnoll
instagram_username: /
linkedin_username: jason-p-knoll
github_username: JasonPKnoll
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
discord_id: 948668827355463782
google-analytics: UA-163806439-1
disqus-shortname: Jason Knoll
author-name: Jason Knoll
author-image: /assets/images/Portrait.jpg
author-about: >-
  A results-driven software developer. I thoroughly enjoy working in unison with
  others to solve complex problems. I have a passion for constant self-growth
  and improvement. Finding fulfillment in work was the most substantial
  contributor to my career transition into Software development. Before finding
  my appreciation for software development, I worked in financial sales for
  seven years. My previous role allowed me to build considerable communication
  through working with over eighty branches in my assigned territory. In
  addition, I developed strong communication with over one hundred and fifty
  colleagues located in different sectors throughout the firm.
author-url: 'https://github.com/JasonPKnoll'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
